### ISSUE TITLE
Getting Error while creating attribute family in Postman, In Admin Panel we are able to see the Family Created.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/headless-ecommerce#67]
## Issue Description
When we create a new Attribute Family via API in Postman, there we can see that the error is appearing after hitting the API. After the API hit when we check the Admin Panel there we can see that the attribute family is created.

## Bagisto Version
V1.4.3

## Steps To Reproduce
1. Go to Postman -> Catalog API Collection -> Attributes Family Section -> Create New Attribute Family. 
2. There when we fill the data and hit the API, then we can see the error appearing.
3.  After that when we check the Admin section there we can see the Family is created.

## Actual Result
Please check the below screenshot and video for a better understanding of the concern.

**POSTMAN COLLECTION**
![Screenshot from 2022-08-22 15-51-38](https://user-images.githubusercontent.com/92721837/185899091-5a06806a-2963-474f-823e-068856d17d71.png)

**Video**

https://user-images.githubusercontent.com/92721837/185899170-527365bd-eb63-4016-bf75-f58508906314.mp4

## Expected Result
We should be able to create a new family without the error appearing in the API. The details should be correct in the API. when we hit the API it should not throw any error.

**Comment by deepaksinghgusain227** [comment]
Fixed in commit id - da1a06b8bea7008d59d794d1331daa5e29ae00c7

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue is not fixed. Please check and fix the concern again.

![Screenshot from 2022-09-12 17-53-07](https://user-images.githubusercontent.com/92721837/189652918-f5f57ebc-ecdc-488e-b111-a77c661ca322.png)

**Comment by vivek-webkul** [comment]
@ashishkumar-webkul 

You are providing the wrong values for the customAttributes index, try after using the correct data.
It's working fine.

**Comment by ashishkumar-webkul** [comment]
**Bagisto - V1.4.3**

Checked the concern and found it working ok. When inserting the correct data in the API and then hitting he API, we are able to see the correct details appearing. For reference I am attaching the video for the reference . Please consider the view, hence I am closing the issue.

**Video**

https://user-images.githubusercontent.com/92721837/190128655-7064aa64-67fd-4900-b122-92ded9eec304.mp4
